const { EzcordClient } = require('./classes/EzcordClient')
module.exports.EzcordClient = EzcordClient
const { Command } = require('./classes/Command')
module.exports.Command = Command
const { Embed } = require('./classes/Embed')
module.exports.Embed = Embed
const { EmbedAuthor } = require('./interfaces/EmbedAuthor')
module.exports.EmbedAuthor = EmbedAuthor
const { EmbedField } = require('./interfaces/EmbedField')
module.exports.EmbedField = EmbedField
const { StatusOptions } = require('./interfaces/StatusOptions')
module.exports.StatusOptions = StatusOptions